SELECT
    m.HVR_ROWID AS "ROW_ID",
    m.MJAHR AS "YEAR",
    m.BUDAT_MKPF As "DATE",
    m.zz_gbrand AS BRAND_ID,
    z.zbrand AS "BRAND_NAME",
    m.MATNR AS "MSEG_MATERIAL_NUMBER",
    ma.MAKTX as "MATERIAL_NAME",
    a.MATERIAL_TYPE_CODE AS "MATERIAL_TYPE_CODE",
    a.MATERIAL_TYPE_DESCRIPTION AS "MATERIAL_TYPE_DESCRIPTION",
    m.BWART AS "MOVEMENT_TYPE_CODE",
    t1.BTEXT as "MOVEMENT_TYPE",
    m.SAKTO AS "G/L_ACCOUNT",
    s.TXT50 AS "G/L_ACCOUNT_NAME",
    m.WAERS AS "lOCAL_CURRENCY",
    b.UKURS AS "CURRENCY_CONVERSION", 
    m.dmbtr AS "AMOUNT_IN_lOCAL_CURRENCY",
    m.dmbtr * ABS(b.ukurs) AS "AMOUNT_IN_USD",
    m.bualt AS "ALTERNATIVE_AMOUNT",
    m.bwtar AS "VALUATION_TYPE", 
    m.menge * q.scc_usd AS "GROUP_Cost_USD",
FROM "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."MSEG" AS m
LEFT JOIN "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."T001" AS cc
ON m.BUKRS = cc.BUKRS AND cc.SPRAS = 'E'
LEFT JOIN "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."SKAT" AS s
ON m.SAKTO = s.SAKNR AND s.SPRAS = 'E' AND cc.KTOPL = s.KTOPL
LEFT JOIN "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."T001W" AS t0
ON m.WERKS = t0.WERKS AND t0.SPRAS = 'E'
LEFT JOIN "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."T156T" AS t1
ON m.BWART = t1.BWART AND m.SOBKZ = t1.SOBKZ AND t1.SPRAS = 'E' AND  t1.kzvbr =''
LEFT JOIN "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."MAKT" AS ma
ON m.MATNR = ma.MATNR AND ma.SPRAS = 'E'
LEFT JOIN "ENTDATA_PUB"."ODH_SAP_MDG_SS"."ZMBRAND_MDG" AS z
ON m.zz_gbrand = z.zzbrandid
LEFT JOIN(
    SELECT ma2.MATNR, ma2.MTART AS MATERIAL_TYPE_CODE, t3.MTBEZ as MATERIAL_TYPE_DESCRIPTION
    FROM "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."MARA" as ma2
    LEFT JOIN "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."T134T" AS t3
    ON ma2.MTART = t3.MTART AND t3.SPRAS = 'E'
    ) AS a
ON m.matnr = a.matnr
LEFT JOIN(
    SELECT
        t.FCURR,
        t.TCURR,
        t.UKURS,
        t.ZZLTDATE
    FROM "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."TCURR" t
    INNER JOIN (
        SELECT
            FCURR,
            MAX(ZZLTDATE) AS MaxDate
        FROM "ENTDATA_PUB"."ODH_SAP_ECC_NA_SS"."TCURR"
        WHERE TCURR = 'USD' AND KURST = 'M'
        GROUP BY FCURR
    ) x
    ON  t.FCURR = x.FCURR
    AND t.ZZLTDATE = x.MaxDate
    WHERE t.TCURR = 'USD' AND KURST = 'M'
     ) as b
ON CASE
    WHEN m.WAERS = 'USD' THEN 'USDN'
    ELSE m.WAERS
    END = b.FCURR
LEFT JOIN ENTDATA_PUB.ODH_SAP_MDG_SS.MARC as i
ON m.werks = i.werks AND m.matnr = i.matnr
LEFT JOIN OPS_DP_PUB.INVENTORY.GROUP_COST_SCC as q
ON q.PRODUCT_CODE = m.MATNR AND m.werks = q.plant_code AND q.organization_code = i.zorgid
WHERE s.saknr IN ('0040640100', '0044890100', '0040650120', '0040650140', '0040650100') AND m.MJAHR = 2025 AND a.MATERIAL_TYPE_DESCRIPTION = 'Finished Material';
